### ISSUE TITLE
Make ublock version of AdGuard filters compatible with Adblock/Adblock Plus

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersCompiler#10]
It says that it's not a valid filter as it misses the necessary `[Adblock Plus 2.0]` (and maybe smth else):
https://uploads.adguard.com/up04_68i9v_Adblock_Plus_Options.png

Let's make it compatible.

**Comment by Mizzick** [comment]
ublock will then need to remove this header, cause in ADB they exclude it before checksum calculation.

**Comment by ameshkov** [comment]
@Mizzick I don't fully understand what are you talking about:)

**Comment by Mizzick** [comment]
I mean if ublock verifies the checksum, it is neccessary to remove this header line before calculation file content checksum.

**Comment by ameshkov** [comment]
It must not work that way on our side, the checksum should be calculated from the full file content.

**Comment by Mizzick** [comment]
But we don't use ublock platform builds. And otherwise it will not be supported by Adblock
