### ISSUE TITLE
Unknown modifier: redirect-rule

### ISSUE THREAD

**Issue by realodix** [AdguardTeam/FiltersCompiler#100]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect-rule

https://github.com/AdguardTeam/FiltersRegistry/blob/b756296aaf8da7951548d9da72e1edde12cbcc29/filters/ThirdParty/filter_120_AdBlockID/diff.txt#L265

```
Error: "Unknown modifier: redirect-rule=googlesyndication_adsbygoogle.js" in the rule: "/adsbygoogle.$redirect-rule=googlesyndication_adsbygoogle.js,script,domain=nekopoi.web.id"
/adsbygoogle.$redirect-rule=googlesyndication_adsbygoogle.js,script,domain=nekopoi.web.id
```

**Comment by ameshkov** [comment]
I don't think we support it in the current version of AG.

We can auto-convert it to $redirect (our implementation has some things similar to `redirect`, but it's still not the same), we should just wait until `redirect-rule` support is added.

**Comment by ameshkov** [comment]
Ah, it seems we've added it to CoreLibs so standalone versions already should support it: https://github.com/AdguardTeam/CoreLibs/issues/1303

The Javascript filtering engine is next: https://github.com/AdguardTeam/tsurlfilter/issues/6 and then we'll be able to update the filters compiler.

**Comment by Alex-302** [comment]
@ameshkov But in CL it works just as `$redirect`, not as in uBO.

**Comment by ameshkov** [comment]
@Alex-302 it's been added in CL 1.8 as `$redirect-rule`, CL 1.8 is not yet released.

**Comment by realodix** [comment]
I don't know if this is a bug or it's not supported, some `redirect-rules` return error messages.

> `Error: "$redirect modifier is invalid" in the rule: "*$image,redirect-rule=1x1.gif,domain=seznamzpravy.cz"`
> [FiltersRegistry/filters/ThirdParty/filter_105_EasyListCzechAndSlovak/diff.txt#L115](https://github.com/AdguardTeam/FiltersRegistry/blob/2943288a412693aeb6b6e9aa1355b3dadec9a403/filters/ThirdParty/filter_105_EasyListCzechAndSlovak/diff.txt#L115)

> `Error: "$redirect modifier is invalid" in the rule: "*$image,redirect-rule=32x32.png,domain=ukr.net"`
> [FiltersRegistry/filters/ThirdParty/filter_115_RUAdList/diff.txt#L2181](https://github.com/AdguardTeam/FiltersRegistry/blob/2943288a412693aeb6b6e9aa1355b3dadec9a403/filters/ThirdParty/filter_115_RUAdList/diff.txt#L2181)

> `Error: "$redirect modifier is invalid" in the rule: "*$script,redirect-rule=noop.js,domain=otzovik.com|ukr.net"`
> [FiltersRegistry/filters/ThirdParty/filter_115_RUAdList/diff.txt#L2183](https://github.com/AdguardTeam/FiltersRegistry/blob/2943288a412693aeb6b6e9aa1355b3dadec9a403/filters/ThirdParty/filter_115_RUAdList/diff.txt#L2183)

> `Error: "$redirect modifier is invalid" in the rule: "||googlesyndication.com^$script,redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws"`
> [FiltersRegistry/filters/ThirdParty/filter_238_PolskiFiltrAdg/diff.txt#L328](https://github.com/AdguardTeam/FiltersRegistry/blob/2943288a412693aeb6b6e9aa1355b3dadec9a403/filters/ThirdParty/filter_238_PolskiFiltrAdg/diff.txt#L328)
