### ISSUE TITLE
Convert abort-on-property-read scriptlet to abort-on-stack-trace if it has the second parameter for uBlock version of lists

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersCompiler#104]
I couldn't find any actual usage but seeing https://github.com/AdguardTeam/FiltersCompiler/blob/38221d2115dca8610199717da75d0d926c176666/src/test/converter.test.js I believe it needs to be addressed. AG's abort-on-property-read can utilize stack trace in the second parameter, while uBO uses a different scriptlet abort-on-stack-trace for that: (https://github.com/gorhill/uBlock-for-firefox-legacy/commit/7099186ae54e70b588d5e99554a05d783cabc8ff). So if abort-on-property-read has the second parameter, it has to be converted to abort-on-stack-trace. AG's set-constant also can use stack trace but I'm not sure how to treat this.

**Comment by slavaleleka** [comment]
no need for such tricky workaround. now we have our own `abort-on-stack-trace` and there is no stack arg for `abort-on-property-read`/`-write` so conversion should be just fine

**Comment by Yuki2718** [comment]
Yeah, it didn't at the time I opened the ticket.
