### ISSUE TITLE
"Redirect:" directive is not removed from the filter

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersCompiler#105]
Filter `https://raw.githubusercontent.com/kargig/greek-adblockplus-filter/master/void-gr-filters.txt` contains `Redirect` directive
`! Redirect: https://www.void.gr/kargig/void-gr-filters.txt`
According to `exclusions.txt` it must be removed by `Redirect:` https://github.com/AdguardTeam/FiltersRegistry/blob/41d5e81b0a01500947f1dfa04b57ec966639bc5a/filters/exclusions.txt#L21
But at the moment Compiler tries to download `https://www.void.gr/kargig/void-gr-filters.txt` (at the moment it fails due to server issue) instead of downloading `https://raw.githubusercontent.com/kargig/greek-adblockplus-filter/master/void-gr-filters.txt`
![image](https://user-images.githubusercontent.com/8361299/111464022-ed068080-8728-11eb-9114-39a7368163b3.png)

**Comment by ameshkov** [comment]
@tvinzz solve this ASAP.

**Comment by ameshkov** [comment]
@Alex-302 погоди, я только осознал. Все нормально, мы специально так ругаемся - иначе мы будем забывать обновлять у фильтров "Redirect" директиву.

**Comment by Alex-302** [comment]
Ну всё равно проблема есть - фильтр не скачивается с сервера, на который редиректит.

**Comment by ameshkov** [comment]
Ну тогда его вырубить пока что нужно. Странно что не скачивается - в браузере нормально открывает

**Comment by Alex-302** [comment]
Похоже он серт обновил. Утром включу обратно.
