### ISSUE TITLE
Unknown modifier: ~xhr

### ISSUE THREAD

**Issue by realodix** [AdguardTeam/FiltersCompiler#107]
https://github.com/AdguardTeam/FiltersRegistry/blob/866fde55ddc3148d23e49eaf4ea6d7950da331cd/filters/ThirdParty/filter_120_AdBlockID/diff.txt#L403

```
Error: "Unknown modifier: ~xhr" in the rule: ".id^*/ad/$~third-party,~image,~xhr"
.id^*/ad/$~third-party,~image,~xhr
Error: "Unknown modifier: ~xhr" in the rule: ".id^*/ad2/$~xhr"
.id^*/ad2/$~xhr
Error: "Unknown modifier: ~xhr" in the rule: ".id^*/ads.$~script,~xhr"
.id^*/ads.$~script,~xhr
```

**Comment by Alex-302** [comment]
> Error: "Unknown modifier: ~xhr" in the rule: ".id^*/ads.$~script,~xhr"

Now it is in the filter:
![image](https://user-images.githubusercontent.com/8361299/120544771-722f3680-c3f6-11eb-8c21-d014ee75f9f3.png)
