### ISSUE TITLE
Allow to apply $removeparam rules to all resources

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/FiltersCompiler#115]
https://github.com/AdguardTeam/tsurlfilter/issues/16

For example, at the moment this rule:
`||brightcove.com/playback/*/*?ad_config_id$removeparam=ad_config_id,xmlhttprequest,domain=tvnz.co.nz`
 is marked as invalid, but shouldn't be.

```
Error: "$removeparam rules are not compatible with some other modifiers" in the rule: "||brightcove.com/playback/*/*?ad_config_id$removeparam=ad_config_id,xmlhttprequest,domain=tvnz.co.nz"
||brightcove.com/playback/*/*?ad_config_id$removeparam=ad_config_id,xmlhttprequest,domain=tvnz.co.nz
```

https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_2_English/diff.txt

**Comment by tvinzz** [comment]
https://github.com/AdguardTeam/tsurlfilter/blob/e3ab4241619d47c09b5a782d1d4cd3c46ef8072d/src/rules/network-rule.ts#L1322
> $removeparam rules are not compatible with any other modifiers except $domain,
> $third-party, $app, $important, $match-case and permitted content type modifiers ($script, $stylesheet, etc).
> The rules with any other modifiers are considered invalid and will be discarded.

**Comment by tvinzz** [comment]
moved there https://github.com/AdguardTeam/tsurlfilter/issues/33

**Comment by AdamWr** [comment]
As far as I know, there is already opened issue in `tsurlfilter` - https://github.com/AdguardTeam/tsurlfilter/issues/16 and I even mentioned it at the begining of my comment :)
