### ISSUE TITLE
Add logging for the rules with hints

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersCompiler#12]
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#hints-1

**Comment by ameshkov** [comment]
Logging?

**Comment by Alex-302** [comment]
Like that
![image](https://user-images.githubusercontent.com/8361299/36797831-a5ec40de-1cb1-11e8-9900-c5aa69adf7f8.png)
