### ISSUE TITLE
Element hiding rules without quotes are marked as invalid

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/FiltersCompiler#123]
Element hiding rules without quotes are marked as invalid (maybe only these with case-insensitive attribute).
```
! Invalid selector:
##div[class*=smart-banner i]:not(.smart-banner-visible)
! Invalid selector:
##div[class*=smartbanner i]
! Invalid selector:
##div[id*=smart-banner i]
! Invalid selector:
##div[id*=smartbanner i]
```

Few examples from - https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_250_DandelionSproutAnnoyances/diff.txt

**Comment by DandelionSprout** [comment]
Doesn't look like tvinzz ever got around to looking into this thread after being assigned to do so. 😅

Since it still seems to be a problem, judging by #139.
