### ISSUE TITLE
Some `redirect-rules` return error messages.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersCompiler#127]
I don't know if this is a bug or it's not supported, some `redirect-rules` return error messages.

> `Error: "$redirect modifier is invalid" in the rule: "*$image,redirect-rule=1x1.gif,domain=seznamzpravy.cz"`
> [FiltersRegistry/filters/ThirdParty/filter_105_EasyListCzechAndSlovak/diff.txt#L115](https://github.com/AdguardTeam/FiltersRegistry/blob/2943288a412693aeb6b6e9aa1355b3dadec9a403/filters/ThirdParty/filter_105_EasyListCzechAndSlovak/diff.txt#L115)

> `Error: "$redirect modifier is invalid" in the rule: "*$image,redirect-rule=32x32.png,domain=ukr.net"`
> [FiltersRegistry/filters/ThirdParty/filter_115_RUAdList/diff.txt#L2181](https://github.com/AdguardTeam/FiltersRegistry/blob/2943288a412693aeb6b6e9aa1355b3dadec9a403/filters/ThirdParty/filter_115_RUAdList/diff.txt#L2181)

> `Error: "$redirect modifier is invalid" in the rule: "*$script,redirect-rule=noop.js,domain=otzovik.com|ukr.net"`
> [FiltersRegistry/filters/ThirdParty/filter_115_RUAdList/diff.txt#L2183](https://github.com/AdguardTeam/FiltersRegistry/blob/2943288a412693aeb6b6e9aa1355b3dadec9a403/filters/ThirdParty/filter_115_RUAdList/diff.txt#L2183)

> `Error: "$redirect modifier is invalid" in the rule: "||googlesyndication.com^$script,redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws"`
> [FiltersRegistry/filters/ThirdParty/filter_238_PolskiFiltrAdg/diff.txt#L328](https://github.com/AdguardTeam/FiltersRegistry/blob/2943288a412693aeb6b6e9aa1355b3dadec9a403/filters/ThirdParty/filter_238_PolskiFiltrAdg/diff.txt#L328)

_Originally posted by @realodix in https://github.com/AdguardTeam/FiltersCompiler/issues/100#issuecomment-975020727_

**Comment by slavaleleka** [comment]
last one about `redirect=googlesyndication.com/adsbygoogle.js` will be fixed in [Scriptlets #162](https://github.com/AdguardTeam/Scriptlets/issues/162)
