### ISSUE TITLE
Hints must be applied to the same rules in all filters

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersCompiler#13]
For example, this rule breaks the sites when used browser extension, but it exists in Liste-FR. It must be excluded from all filters.
```
!+ PLATFORM(windows, mac, android)
||piguiqproxy.com^$third-party
``

**Comment by ameshkov** [comment]
As I understand, you can make `!+ PLATFORM` work on a filter-level, it cannot be global. If you want it to be global, you'll need to include it in every filter.

I really thing `exclusions` is what we need in this particular case.
