### ISSUE TITLE
Valid redirect rule `redirect=fingerprint2.js` marked as invalid

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersCompiler#132]
`Invalid rule: ||cloudflare.com/ajax/libs/fingerprintjs2/$script,redirect=fingerprint2.js,domain=gamebox.gesoten.com,important
Compiled length:27562`
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-redirects.md#-%EF%B8%8F-fingerprintjs

**Comment by slavaleleka** [comment]
it should be fixed in filters

AdGuard name of this redirect is `fingerprintjs`

**Comment by Alex-302** [comment]
Fixed. But in any case we can add alias for uBO.

**Comment by slavaleleka** [comment]
Issue moved to [AdguardTeam/Scriptlets #187](https://github.com/AdguardTeam/Scriptlets/issues/187) via [**ZenHub**](https://www.zenhub.com/)
