### ISSUE TITLE
Add support for `redirect-rules` for "configuration.removeRulePatterns"

### ISSUE THREAD

**Issue by gontazaka** [AdguardTeam/FiltersCompiler#137]
For example...
`\\$redirect=` -> `\\$redirect(-rule)?=`
`,redirect=` -> `,redirect(-rule)?=`
cf. https://github.com/AdguardTeam/FiltersCompiler/blob/v1.1.35/platforms.json#L64-L65

**Comment by slavaleleka** [comment]
what problem you have faced?

**Comment by ameshkov** [comment]
@slavaleleka "redirect-rule" should also be added to the "removeRulePatterns" for iOS filters.
