### ISSUE TITLE
Filters compiler fails to transform the `:style` rules properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersCompiler#14]
See the details here:
https://github.com/AdguardTeam/ContentBlocker/issues/107#issuecomment-372024790

Problematic rules:
```
apkmirror.com##body .google-ad-leaderboard-smaller:style(position: absolute!important; left: -4000px!important; display:block!important;)
apkmirror.com##body .google-ad-square-sidebar:style(position: absolute!important; left: -4000px!important; display:block!important;)
```

Both rules should've been transformed into the `#$#` syntax, but they didn't:
```
apkmirror.com#$#body .google-ad-leaderboard-smaller { position: absolute!important; left: -4000px!important; display:block!important; }
apkmirror.com#$#body .google-ad-square-sidebar { position: absolute!important; left: -4000px!important; display:block!important; }
```

**Comment by ameshkov** [comment]
@Mizzick smth is still not okay:
https://github.com/AdguardTeam/ContentBlocker/issues/107#issuecomment-381290721

**Comment by Mizzick** [comment]
the rules are in place:
https://filters.adtidy.org/extension/chromium/filters/2.txt
Most probably it was filtered for content-blocker.

**Comment by Mizzick** [comment]
Indeed, we omit `"#%#", "#@%#", "#$#", "#@$#",` rules.
