### ISSUE TITLE
Include set-cookie and set-cookie-reload scriptlet rules in all uBO version of lists

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersCompiler#181]
As now supported except that reload is done by optional parameter than a dedicated scriptlet: https://github.com/gorhill/uBlock/commit/112e41b9d5a2229dbdc139caaa9ac7a2dfc38729

**Comment by krystian3w** [comment]
Also I saw new values unsupported by AdGuard `set-cookie` based on AG md file:
```
y|Y
n|N
```

**Comment by slavaleleka** [comment]
done in [Scriptlets v1.10](https://github.com/AdguardTeam/Scriptlets/blob/master/CHANGELOG.md#v1101---2024-02-12)
