### ISSUE TITLE
Convert `set-cookie-reload` to uBO's syntax

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersCompiler#187]
For example:
`tumblr.com#%#//scriptlet('set-cookie-reload', 'logged_in', '1')`
to
`tumblr.com##+js(set-cookie, logged_in, 1, , reload, 1)`

**Comment by slavaleleka** [comment]
related
https://github.com/AdguardTeam/FiltersCompiler/issues/181
