### ISSUE TITLE
forum.ixbt.com - page scrolls to top after watching uploaded image

### ISSUE THREAD

**Issue by lansman** [AdguardTeam/FiltersCompiler#196]
Go to any forum topic.
Find a post with uploaded image, [for example](https://forum.ixbt.com/topic.cgi?id=8:26203:3028#3028)
Click the image to expand.
After this your web-page scrolls to the top, this is annoying, cause you have to scroll down again to find the post you read.

If you disable ublock on the web site - issue doesn't occur.

I was sent here by https://github.com/uBlockOrigin/uAssets/issues/20405#issuecomment-1789873325

**Comment by gorhill** [comment]
Filter causing issue is `ixbt.com##body:style(overflow: auto !important;)`

**Comment by gorhill** [comment]
Sorry, I posted wrong link, it should have been <https://github.com/AdguardTeam/AdguardFilters/issues>

**Comment by lansman** [comment]
> Sorry, I posted wrong link, it should have been https://github.com/AdguardTeam/AdguardFilters/issues

Could you move the issue there or should i recreate manually?

**Comment by lansman** [comment]
Done https://github.com/AdguardTeam/AdguardFilters/issues/165200
