### ISSUE TITLE
Remove unsupported modifiers from AG for Safari filter lists

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/FiltersCompiler#201]
Examples of unsupported modifiers according to
https://adguard.com/kb/general/ad-filtering/create-own-filters/
but present in  AG for Safari filter lists:

`||adtclickwhite.com^$all`

`@@||findernet.com^$content`

found in
https://filters.adtidy.org/extension/safari/filters/2.txt

**Comment by slavaleleka** [comment]
`$all` is actually supported by Adguard for Safari and Adguard for iOS so Knowledge Base should be updated
