### ISSUE TITLE
Convert uBO's `+js(set-local-storage-item)` to AdGuard syntax

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersCompiler#205]
`zippia.com##+js(set-local-storage-item, gatedSignupTimerCounter, $remove$)` considered as invalid
`Error: Invalid selector: '+js(set-local-storage-item, gatedSignupTimerCounter, $remove$)' -- '+js(set-local-storage-item, gatedSignupTimerCounter, $remove$)' is not a valid selector in rule: zippia.com##+js(set-local-storage-item, gatedSignupTimerCounter, $remove$)`

**Comment by slavaleleka** [comment]
fixed in [v1.1.127](https://github.com/AdguardTeam/FiltersCompiler/blob/v1.1.127/CHANGELOG.md)
