### ISSUE TITLE
`$replace` rule with `$1$2` replacement considered as invalid

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersCompiler#208]
```
Filter name: AdGuard Base filter
Error: "Unknown modifier: 2/" in the rule: "||serverside.ai/vod/mpds/*.mpd$replace=/(<BaseURL>).*?\/ad\/.*?(<\/BaseURL>)/$1$2/"
```

**Comment by maximtop** [comment]
> ```
> Filter name: AdGuard Base filter
> Error: "Unknown modifier: 2/" in the rule: "||serverside.ai/vod/mpds/*.mpd$replace=/(<BaseURL>).*?\/ad\/.*?(<\/BaseURL>)/$1$2/"
> ```

https://adguard.com/kb/general/ad-filtering/create-own-filters/#replace-modifier

>In the $replace value, two characters must be escaped: comma , and dollar sign **$**. Use backslash \ for it. For example, an escaped comma looks like this: \,.
