### ISSUE TITLE
`!#include` directive problem

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersCompiler#220]
`https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuard.txt` 
has (had - it was updated) the directive
`!#include uBO%20list%20extensions/Dandelion%20Sprout's%20Anti-Malware%20List%20—%20AdGuardOnlyEntries.txt`

### Actual behaviour

AdGuard transform path to non existing
`https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/uBO%20list%20extensions/Dandelion%20Sprout's%20Anti-Malware%20List%20—%20AdGuardOnlyEntries.txt`

### Expected behaviour

Correct path (like in uBO):
`https://raw.githubusercontent.com/DandelionSprout/adfilt/master/uBO%20list%20extensions/Dandelion%20Sprout's%20Anti-Malware%20List%20—%20AdGuardOnlyEntries.txt`

Our and uBO's specs are not fully compatible

* AdGuard:
https://adguard.com/kb/general/ad-filtering/create-own-filters/#include-directive
* uBO:
https://github.com/gorhill/ublock/wiki/Static-filter-syntax#include-file-name

**Comment by ameshkov** [comment]
In addition to that, AdGuard should verify that the included file is inside the directory where the parent file is located.

I.e., for a file `/dir1/dir2/filter.txt`
```
! Allowed:
!#include /dir1/dir2/inclusion.txt
!#include /dir1/dir2/dir3/inclusion.txt
!#include /dir1/dir2/dir3/dir4/inclusion.txt

! Not allowed:
!#include /dir1/inclusion.txt
```

**Comment by Alex-302** [comment]
Moved to https://github.com/AdguardTeam/FiltersDownloader/issues/27
