### ISSUE TITLE
Convert set-cookie-reload to set-cookie for uBO version of lists

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersCompiler#224]
https://github.com/gorhill/uBlock/wiki/Resources-Library#set-cookiejs-
No support for `set-cookie-reload` but `set-cookie` with `reload, 1`; E.g. `tumblr.com##+js(set-cookie, logged_in, 1, , reload, 1)`.

**Comment by slavaleleka** [comment]
ubo supports `set-cookie-reload` so conversion by FiltersCompiler may not be needed
https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js#L3820

**Comment by Yuki2718** [comment]
Confirmed, it's working. Sorry for bothering.
