### ISSUE TITLE
Unsupported rules in iOS and Safari filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersCompiler#28]
@Alex-302 commented on [Tue Nov 13 2018](https://github.com/AdguardTeam/FiltersRegistry/issues/121)

* iOS
`$network`
`$empty` / `,empty`
`$csp=`
`$webrtc`
* Safari
`$empty` / `,empty`
`$webrtc`

**Comment by Alex-302** [comment]
also `,stealth`(Stealh mode exclusion) in browser extension filters
For example `@@||i.tmgrup.com.tr^$script,stealth`

**Comment by ameshkov** [comment]
@Alex-302 browser extension will support stealth starting with v3
