### ISSUE TITLE
Pre-processor directives are ignored in optimized filters

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/FiltersCompiler#32]
For example these rules shouldn't be available in filters for Android app - https://github.com/AdguardTeam/AdguardFilters/blob/3a61398e615de3a475c1c4ba888db30520efa14a/RussianFilter/sections/antiadblock.txt#L1382-L1428, but they are still here - https://filters.adtidy.org/android/filters/1_optimized.txt

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/48639949-85fc2400-e9d5-11e8-9a12-fe2ed2f3c380.png)

</details>

**Comment by Mizzick** [comment]
Fixed
