### ISSUE TITLE
Add scheme validation script

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersCompiler#34]
Additionally to the build script we should provide JSON scheme validation (for monitoring purposes).

* https://json-schema.org/
* https://www.npmjs.com/package/jsonschema

Here's what needs to be validated:

* `filters.json` (for every platform)
* `filters_i18n.json` (for every platform)
* number of filters in the filters.json (hardcode `>= 80`)

How it should work:
`node validate.js path_to_platforms_directory`

**Comment by Mizzick** [comment]
Fixed
