### ISSUE TITLE
Add a validity checking for rules with domain modifier

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/FiltersCompiler#38]
Rules like these:
`|http*$domain=|example.org`
`|http*$script,domain=|example.org`
should be treated as invalid or converted to:
`|http*$domain=example.org`
`|http*$script,domain=example.org`
otherwise they are applied to all websites due to `domain=|`

**Comment by Mizzick** [comment]
Fixed https://github.com/AdguardTeam/FiltersCompiler/releases/tag/v1.0.27
