### ISSUE TITLE
Exclude ABP snippets

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersCompiler#39]
https://easylist-downloads.adblockplus.org/easylist.txt

The rules like `#$#abort-current-inline-script matchmedia`

By the way, how does it pass CSS rules validation?

**Comment by slavaleleka** [comment]
it seems to be fixed by [`#$#abort-current-inline-script` exclusion](https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/exclusions.txt#L9)

but compiler is able to convert ABP snippets now. so should we really exclude them?

**Comment by ameshkov** [comment]
Well, it'd be better to convert them indeed.
