### ISSUE TITLE
Rules with case-insensitive attribute are treated as invalid

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/FiltersCompiler#41]
For example rule like this:
`samdan.com.tr,esquire.com.tr##div[data-mbzone="Textlink" i] > div#id_d_textlink`
The problem is with `i` in `div[data-mbzone="Textlink" i]`

**Comment by Alex-302** [comment]
@Mizzick *ping*

**Comment by AdamWr** [comment]
It seems that some rules are still treated as invalid, for example:
```
! Invalid selector:
##a[title*="zeupoker" i] > img
! Invalid selector:
##img[alt*="QQ online" i]
```
from here - https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_120_AdBlockID/diff.txt

and from here - https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_102_ABPindo/diff.txt
```
! Invalid selector:
##img[alt="sepakbola.cc" i]
```

**Comment by realodix** [comment]
Why is this closed?  Open this https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_120_AdBlockID/diff.txt#L120

It seems that some rules are still treated as invalid

**Comment by ameshkov** [comment]
@realodix we have not yet applied the new filters compiler version. It should be done soon.
