### ISSUE TITLE
Remove extCSS rules from iOS filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersCompiler#45]
`#?#`
`#$?#`
`#@$?#`
`#@?#`

**Comment by Mizzick** [comment]
Already done

**Comment by slavaleleka** [comment]
if I'm not mistaken, there are still such rules

for example
![Screenshot 2019-07-17 at 17 23 39](https://user-images.githubusercontent.com/45171506/61384028-714f9300-a8b8-11e9-81f0-d2068b35fe09.png)

**Comment by Mizzick** [comment]
ok, got it

**Comment by Mizzick** [comment]
Fxied
