### ISSUE TITLE
$mp4 rule is not compiled into FF extension list

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/FiltersCompiler#48]
Rule `||smrmembers-smr.smartmediarep.com/smc/smrmembers^$mp4,important` is not found in Base filter for FF extension:

https://filters.adtidy.org/extension/firefox/filters/2.txt

$mp4 and $important are supported by FF extension

**Comment by Mizzick** [comment]
Do you want to allow such rules for FF?

**Comment by BlazDT** [comment]
Yes, they block video ads fine.

**Comment by Mizzick** [comment]
FF only or other extensions aswell?

**Comment by BlazDT** [comment]
Only FF supports $mp4 of the extensions.

**Comment by AdamWr** [comment]
>Only FF supports $mp4 of the extensions.

Are you sure about this?
If I'm not wrong other extension should support it too and as I see it works with Chrome extension.
It's converted to:
`||smrmembers-smr.smartmediarep.com/smc/smrmembers^$redirect=noopmp4-1s,important`

**Comment by BlazDT** [comment]
Adam, that is $redirect. Did not know it will be converted.

**Comment by AdamWr** [comment]
Ok, I just meant, that if you add to extenstion:
`||smrmembers-smr.smartmediarep.com/smc/smrmembers^$mp4,important`
it will convert it to:
`||smrmembers-smr.smartmediarep.com/smc/smrmembers^$redirect=noopmp4-1s,important`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/61734996-4e732200-ad83-11e9-8a41-6bdea2bdbf2e.png)

</details>

**Comment by BlazDT** [comment]
Then it seems it is only not active for FF extension.

**Comment by Mizzick** [comment]
Actually not, rules with `$mp4` modifier are currently omitted  for chromium, opera, ff, ublock and some others.

**Comment by AdamWr** [comment]
No, it's not available in Chrome extension too, I added it to user filter to check if it works.

**Comment by BlazDT** [comment]
OK, please implement for FF and Chrome then.
