### ISSUE TITLE
Automatically convert uBO and ABP scriptlets to AdGuard scriptlets

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersCompiler#52]
`Invalid selector: filmweb.pl#@#+js(abort-current-inline-script.js, Math.random, adbDetect)`
`Invalid selector: filmweb.pl#@#+js(setTimeout-defuser.js, notDetected)`

**Comment by ameshkov** [comment]
While newer versions of AdGuard are capable of doing it on their own, we should do this on the server-side anyway.

You should use the [Scriptlets library](https://github.com/AdguardTeam/Scriptlets) to:

1. Apply conversion rules
2. Validate rules

**Comment by krystian3w** [comment]
I found bug with CJX:

```
! dlkoo.com#%#//scriptlet('ubo-acis,setTimeout,testad.js') is excluded by "#%#//scriptlet" in exclusions-low.txt
dlkoo.com#%#//scriptlet('ubo-acis,setTimeout,testad.js')
```

Origin allow not use spaces:

`dlkoo.com##+js(acis,setTimeout,testad)`
