### ISSUE TITLE
option $all marked as invalid in filters registry

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/FiltersCompiler#58]
> https://github.com/AdguardTeam/FiltersRegistry/blob/3ee312f700102d078ee539f4bce67186ca649da1/filters/ThirdParty/filter_232_KADPrzekrety/diff.txt#L5-L6

**Comment by krystian3w** [comment]
When subscribe manually from github works OK with AdGuard Adblocker add-on.

**Comment by ameshkov** [comment]
Thank you!

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersCompiler/pull/59 - Follow this: #61 ???

❓
