### ISSUE TITLE
Convert ##^script:has-text to $$script[tag-containts]

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersCompiler#60]
See how this task was implemented in the browser extension:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1452

We should do this on the server-side to avoid messing with the old AdGuard versions that don't understand this type of rules automatically.

Please note, that if the `##^` cannot be converted automatically for some reasons, it should be considered invalid.

**Comment by krystian3w** [comment]
no typo? 

`$$script[tag-containts]` vs https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#tag-content-attribute

**Comment by ameshkov** [comment]
Uh, that's my bad! We'll fix it asap

**Comment by krystian3w** [comment]
```
! bartek.com.pl##^script:has-text(popupNewsletter) is excluded by: ##^
bartek.com.pl##^script:has-text(popupNewsletter)
```

https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_237_PolishAnnoyance/diff.txt#L63-L64

No need rebuild https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/exclusions.txt?

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/280
