### ISSUE TITLE
Convert $redirect rules to uBO syntax

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersCompiler#68]
See this task:
https://github.com/AdguardTeam/FiltersCompiler/issues/56

It makes sense to do the same for $redirect rules.

There's on important thing about them, though. In uBO, $redirect rules must contain a resource-type modifier, which we do not require in AdGuard.

What should we do with that? Should we add it automatically or should we make it a requirement for our filter lists?

**Comment by tvinzz** [comment]
I guess we should add it automatically
