### ISSUE TITLE
URL blocking rules with `$document,popup` do nothing in Safari for Mac and iOS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersCompiler#74]
For example, `||vpn5protectplus.com^$document,popup` in Chrome completely block the page(replaced by blocking page) on direct visit, or closes tab in case of popup.
`||vpn5protectplus.com^$document` works as `||vpn5protectplus.com^` - blocks the page.
`||vpn5protectplus.com^$popup` does nothing in Safari and iOS.
It seems `popup` modifier must be removed.
But `||vpn5protectplus.com^$all` works in Safari - block content of new tab.

**Comment by floam** [comment]
Fixed?

**Comment by ameshkov** [comment]
As I recall it was fixed in Safari app -- `||vpn5protectplus.com^$popup` now should block the whole page. Not sure if we already released that update.
