### ISSUE TITLE
Some redirect rules are marked as invalid

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/FiltersCompiler#75]
For example:
> ! Invalid redirect rule:
||ad.mail.ru/vast/*&duration=$domain=khl.ru,xmlhttprequest,redirect=noopvast-2.0,important
! Invalid redirect rule:
||strm.yandex.ru/get/$script,redirect=noopvast-2.0,domain=kinopoisk.ru
! Invalid redirect rule:
||wasd.tv/ssp/roll$redirect=noopvast-2.0
! Invalid redirect rule:
||vast*.kinogo.by/code/video-steam/?id=$redirect=noopvast-2.0
! Invalid redirect rule:
||anime.anidub.life/player/vast.php$redirect=noopvast-3.0
! Invalid redirect rule:
||online.anidub.com/player/vast.php$redirect=noopvast-3.0
! Invalid redirect rule:
||oneseasons.club/*.xml$redirect=noopvast-3.0

https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_1_Russian/diff.txt#L8

and

> ! Invalid redirect rule:
||tvn.adocean.pl/*ad.xml$xmlhttprequest,redirect=noopvast-2.0,domain=tvn24.pl
! Invalid redirect rule:
||ipla.hit.stat24.com/*ad.xml$xmlhttprequest,redirect=noopvast-2.0,important,domain=twojapogoda.pl

https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_2_English/diff.txt#L170

**Comment by ameshkov** [comment]
@tvinzz old scriptlets library?

**Comment by tvinzz** [comment]
There were no changes at redirects after scriptlets release v1.1.6
But anyway I updated to the last version v.1.1.10 and also have redirects validation problem with `isValidAdgRedirectRule` method.

**Comment by ameshkov** [comment]
@tvinzz well, we should figure out what's wrong with it then

**Comment by AdamWr** [comment]
If I understand correctly, this issue has been fixed, but now (or maybe it was before too) the problem is with `$redirect=noopmp3-0.1s`
Rule:
```
! Invalid redirect rule:
||podu.me/ads/audio/*.mp3$redirect=noopmp3-0.1s
```

https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_2_English/diff.txt#L155-L156
