### ISSUE TITLE
Add support for ":scope"

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/FiltersCompiler#77]
Pretty much what the title says.

`:has(:scope` is a gods-send in all other browser-based adblockers (Even in Adblock Plus, although as `:-abp-has(:scope` there), as it enables `:has` to only select immediate child elements.

For example, something like `example.org##div:has(:scope > .blockedelement)` would work very well; whereas `example.org##div:has(.blockedelement)` and (unless my personal testing has been completely wrong) `example.org##div:has(> .blockedelement)` would be a death wish on the listmaker's part because it'd e.g. select the `div` immediately below `body` in the filetree.

I also can't find any significant reasons for why AdGuard doesn't support it, so I hereby propose that you could support it. Currently, ~18 entries in my Nordic list hinges entirely on `:scope` being supported somehow (incl. ones with `:upward`, which I know a good conversion for once `:scope` becomes supported).

Alternately, whichever other method(s) of only selecting immediate child elements would also have been great.

Tested with AdGuard for Windows, version 7.3.3048.0.

**Comment by DandelionSprout** [comment]
After additional testing, it appears that yes, my testing had indeed been completely wrong. `(>` does select immediate children only.

So I will instead propose that `(:scope >` becomes converted to `(>`, instead of being discarded.

**Comment by DandelionSprout** [comment]
Okay, so apparently I've been informed on Slack that `:scope >` can support multiple levels of child elements, whereas `(>` can only select one.

So while even I can tell that it would be non-trivial to add full support for `:scope` then, I think it'd be worth it. And for `:scope` entries where only one child is specified, I think a conversion instead of discardment would still be a pretty good thing.

**Comment by ameshkov** [comment]
In AdGurd you can simply write `:has(> blahblah)`

**Comment by ameshkov** [comment]
> Okay, so apparently I've been informed on Slack that (:scope > can support multiple levels of child elements, whereas (> can only select one.

What do you mean? Any examples?

**Comment by slavaleleka** [comment]
implementing 'scope' support has already been planned, hasn't it?
https://github.com/AdguardTeam/ExtendedCss/issues/101

**Comment by DandelionSprout** [comment]
>What do you mean? Any examples?

From what I was told by JSpenguin2017 on Slack, something like `kanalfrederikshavn.dk#?#div:-abp-has(> div > .boxbanner)` would not have been able to work, because the first `div` in that entry would not have been inherent...

...except it did work, now that I tested it out in a hurry after waking up from a nap. 😶 

Adblock syntaxes and CSS properties are the gifts that just keeps on giving, it seems... 😅

**Comment by ameshkov** [comment]
Yep, I'll close this as dup of https://github.com/AdguardTeam/ExtendedCss/issues/101 then

We'll add `:scope` support for compatibility purposes (internally, we'll simply remove it).

**Comment by gwarser** [comment]
`:scope` is needed to differentiate between `a > target > unspecified > b` tree and `target > unspecified > a > unspecified > b`.

`target:has(a b)` will select both. `target:has(:scope a b)` only second one.

**Comment by ameshkov** [comment]
@gwarser yep, in AG we just have `target:has(> a b)` for exactly that because it's compatible with the CSS spec. We don't mind adding an alias, though.

**Comment by ameshkov** [comment]
Oh wait, now I am confused. How can `target:has(a b)` select the first tree? `a b` must be in the `target`'s subtree in any case.

**Comment by gwarser** [comment]
> How can `target:has(a b)` select the first tree?

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll#JavaScript

**Comment by ameshkov** [comment]
There is no :has pseudo in javascript. Initially, we followed CSS4 draft spec to add its support. It was removed from the draft in the end, but still.

**Comment by gwarser** [comment]
JS api is used internally anyway, so it's used as-is when possible. And it also has some issues - for ex. [returns empty list for sibling selectors](https://www.reddit.com/r/uBlockOrigin/comments/c6iem5/) (`:scope + p`). So now uBO is automatically adding `:scope` [only for child combinator (`>`)](https://github.com/gorhill/uBlock/commit/c1bdc123f243565e5899dd2b8629480fb4477d8a#diff-1c951eedcd0be2e11c02da8fabcc46b5L181).

**Comment by ameshkov** [comment]
Yeah, this makes sense indeed.
