### ISSUE TITLE
Wrongly converted scriptlet rule

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersCompiler#83]
I found bug with CJX:

```
! dlkoo.com#%#//scriptlet('ubo-acis,setTimeout,testad.js') is excluded by "#%#//scriptlet" in exclusions-low.txt
dlkoo.com#%#//scriptlet('ubo-acis,setTimeout,testad.js')
```

Origin allow not use spaces:

`dlkoo.com##+js(acis,setTimeout,testad)`

_Originally posted by @krystian3w in https://github.com/AdguardTeam/FiltersCompiler/issues/52#issuecomment-642854883_

**Comment by slavaleleka** [comment]
Issue moved to [AdguardTeam/Scriptlets #99](https://github.com/AdguardTeam/Scriptlets/issues/99) via [**ZenHub**](https://www.zenhub.com/)
