### ISSUE TITLE
Add support for $removeparam modifier

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/FiltersCompiler#86]

**Comment by AdamWr** [comment]
As far as I know AdGuard v7.5 has been released and if I'm not wrong `$removeparam` is supported by this version, so I would like to remind about this issue.

There is one website which is broken by `Stealth Mode - Strip URLs from tracking parameters` and in this case `$stealth` modifier doesn't fix the problem and `$removeparam` is required.

Steps to reproduce:
1. Enable `Stealth Mode` and `Strip URLs from tracking parameters`
2. Go here -  [https://www.komputerswiat.pl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.komputerswiat.pl/)
3. Click on any article
4. After clicking on article website will redirect to `onet.pl` and there should be a link to "read more", but it's broken due to removed parameter

**Comment by tvinzz** [comment]
$removeparam modifier supported in tsurlfilter

**Comment by AdamWr** [comment]
I'm not sure if I understand correctly, but at the moment rule with `$removeparam` is marked as `Invalid rule options` - https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_2_English/diff.txt#L175-L176

**Comment by tvinzz** [comment]
tsurlfilter is already in compiler. as soon as we release compiler and update it's version in FiltersRegistry the rules with `$removearam` modifier will become valid

**Comment by AdamWr** [comment]
Ok, thank you for your answer.

**Comment by ameshkov** [comment]
@AdamWr tsurlfilter is a new filtering engine we're going to use in the browser extension: https://www.npmjs.com/package/@adguard/tsurlfilter

We'll also be using it in different tools like compiler.

**Comment by AdamWr** [comment]
Okay, thank you for the information.
