### ISSUE TITLE
Regarding "=noopvmap-1.0" and uBO

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/FiltersCompiler#96]
If what AdamWr is saying throughout https://github.com/AdguardTeam/AdguardFilters/issues/68028 is true, does that mean that the `=noopvmap-1.0` pattern should be added as a to-be-removed pattern for uBlock Origin list versions in https://github.com/AdguardTeam/FiltersCompiler/blob/master/platforms.json?

**Comment by slavaleleka** [comment]
we shall skip uBO-unsupported redirects while conversion

**Comment by ameshkov** [comment]
Shall we? It's hard to figure which one is supported or not, and uBO discards unsupported redirects anyways
